site_name: Atrapa un Millón IA

theme:
  name: material
  language: es
  features:
    - navigation.tabs # Crea pestañas en la parte superior
    - navigation.top # Botón para volver arriba
    - search.suggest # Sugerencias al buscar
    - search.highlight # Resalta el texto buscado
  palette:
    # Modo Claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    # Modo Oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - mkdocstrings:
      handlers:
        python: {}

nav:
  - Inicio: index.md
  - Referencia del Código: referencia.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

repo_url: https://github.com/VictorDeMarco/S16-Grupo4
repo_name: Atrapa un Millón IA